### ISSUE TITLE
Make our website responsive

### ISSUE THREAD

**Issue by h0shizaki** [SE331-2023-project1/project01-prakradodkamphaeng#11]
As a user,
I want this website to be responsive,
So that I can access and use this site  seamlessly across various devices, including desktop computers, tablets, and smartphones.

**Comment by ManSmooth** [comment]
Addressed in c3b1c219d919cb82ddbf195e30d0a6cb8cf6a1a2

**Comment by ManSmooth** [comment]
Tweaked in later commits
