### ISSUE TITLE
Implement Add Teacher Page

### ISSUE THREAD

**Issue by h0shizaki** [SE331-2023-project1/project01-prakradodkamphaeng#16]
As a school administrator,
I want to have an "Add Teacher" page in the administrative panel of the system,
So that I can easily add new teachers to the system with their first name, last name, and profile image.

Acceptance Criteria:
1. On the "Add Teacher" page, I should see a form with fields for entering teacher information, including:
* First Name
* Last Name
* Profile Image Upload (with the ability to select and upload an image file)
* Educational information

2. The form should have clear and concise labels for each field, making it easy for me to understand what information is required.
3. There should be a "Submit" button at the bottom of the form that allows me to save the teacher's information.

**Comment by ManSmooth** [comment]
#20
