### ISSUE TITLE
Create student detail page 

### ISSUE THREAD

**Issue by h0shizaki** [SE331-2023-project1/project01-prakradodkamphaeng#2]
As a school administrator,
I want to view detailed information about a specific student,
So that I can access their student ID, first name, last name, enrolled courses, and advisor.

Acceptance Criteria:

1) When I navigate to the Student Detail Page,
* I should see a clear header indicating that I am on the Student Detail Page.
* I should be able to input the student's ID, first name, and last name in a search field.
* Upon entering the student's ID, first name, or last name and clicking the "Search" button,

2) The student's information should be displayed, including:
* Student ID
* First Name
* Last Name
* Under the student's basic information, a section should show the student's enrolled courses,

3) Each enrolled course should be displayed with its course code, course title, and instructor name.
* The student's assigned advisor should be prominently displayed on the page,

4) The advisor's name and contact information (if applicable) should be visible.
* If no student is found with the provided ID, first name, or last name,

5) A clear message should be displayed indicating that no student information was found.
* The page should have a clear and intuitive layout,

6) All information should be neatly organized and easy to read.

**Comment by ManSmooth** [comment]
c0b6b816b36e84e1693c23a4b9e7a7b9a92565bb
